version: 2.1

workflows:
  test:
    jobs:
      # playwright_version
      # https://mcr.microsoft.com/v2/playwright/tags/list
      #
      # playwright_python_version
      # https://pypi.org/project/playwright/#history
      #
      - playwright_server_119:
          playwright_version: 1.18.1
          playwright_python_version: 1.18.1
      - browser_server_119:
          playwright_version: 1.18.1
          playwright_python_version: 1.18.1
      - playwright_server_119:
          playwright_version: 1.19.1
          playwright_python_version: 1.19.1
      - browser_server_119:
          playwright_version: 1.19.1
          playwright_python_version: 1.19.1
      - playwright_server:
          playwright_version: 1.20.0
          playwright_python_version: 1.20.0
      - browser_server:
          playwright_version: 1.20.0
          playwright_python_version: 1.20.0


jobs:
  playwright_server_119:
    parameters:
      playwright_version:
        type: string
      playwright_python_version:
        type: string
    docker:
      - image: python:3.9-alpine
        environment:
          PLAYWRIGHT_SERVER_WS_ENDPOINT: ws://127.0.0.1:8000/ws
      - image: mcr.microsoft.com/playwright:v<< parameters.playwright_version >>
        command: npx playwright@<< parameters.playwright_version >> run-server 8000
        environment:
          npm_config_unsafe_perm: 'true'
          npm_config_yes: 'true'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add build-base curl git
            pip install git+https://github.com/microsoft/playwright-python@v<< parameters.playwright_python_version >>
      - run:
          name: Install dependencies for test
          command: |
            apk add jpeg-dev zlib-dev
            pip install pillow pytest
      - run:
          name: Run tests
          command: pytest tests/test_playwright_server.py

  browser_server_119:
    parameters:
      playwright_version:
        type: string
      playwright_python_version:
        type: string
    docker:
      - image: python:3.9-alpine
        environment:
          BROWSER_SERVER_WS_ENDPOINT: ws://127.0.0.1:8000/playwright
      - image: mcr.microsoft.com/playwright:v<< parameters.playwright_version >>
        command: /bin/bash -c "echo '{\"port\":8000,\"wsPath\":\"playwright\"}' > pl_sock && npx playwright@<< parameters.playwright_version >> launch-server chromium pl_sock"
        environment:
          npm_config_unsafe_perm: 'true'
          npm_config_yes: 'true'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add build-base curl git
            pip install git+https://github.com/microsoft/playwright-python@v<< parameters.playwright_python_version >>
      - run:
          name: Install dependencies for test
          command: |
            apk add jpeg-dev zlib-dev
            pip install pillow pytest
      - run:
          name: Run tests
          command: pytest tests/test_browser_server.py

  playwright_server:
    parameters:
      playwright_version:
        type: string
      playwright_python_version:
        type: string
    docker:
      - image: python:3.9-alpine
        environment:
          PLAYWRIGHT_SERVER_WS_ENDPOINT: ws://127.0.0.1:8000/ws
      - image: mcr.microsoft.com/playwright:v<< parameters.playwright_version >>
        command: npx playwright@<< parameters.playwright_version >> run-server --port 8000 --path /ws
        environment:
          npm_config_unsafe_perm: 'true'
          npm_config_yes: 'true'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add build-base curl git
            pip install git+https://github.com/microsoft/playwright-python@v<< parameters.playwright_python_version >>
      - run:
          name: Install dependencies for test
          command: |
            apk add jpeg-dev zlib-dev
            pip install pillow pytest
      - run:
          name: Run tests
          command: pytest tests/test_playwright_server.py

  browser_server:
    parameters:
      playwright_version:
        type: string
      playwright_python_version:
        type: string
    docker:
      - image: python:3.9-alpine
        environment:
          BROWSER_SERVER_WS_ENDPOINT: ws://127.0.0.1:8000/playwright
      - image: mcr.microsoft.com/playwright:v<< parameters.playwright_version >>
        command: /bin/bash -c "echo '{\"port\":8000,\"wsPath\":\"playwright\"}' > pl_sock && npx playwright@<< parameters.playwright_version >> launch-server --browser chromium --config pl_sock"
        environment:
          npm_config_unsafe_perm: 'true'
          npm_config_yes: 'true'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add build-base curl git
            pip install git+https://github.com/microsoft/playwright-python@v<< parameters.playwright_python_version >>
      - run:
          name: Install dependencies for test
          command: |
            apk add jpeg-dev zlib-dev
            pip install pillow pytest
      - run:
          name: Run tests
          command: pytest tests/test_browser_server.py
